Welcome to your third programming assignment! We have so far learned how to implement a linear regression model for regression task and implement a logistic regression model for classification task. The essential steps in the implementations are:

1. Define your hypothesis, for example $h_w(x) = w^Tx$ for linear regression model where both $w$ and $x$ are vectors;

2. Define your cost or total loss function, and given the training data, calculate the cost or total loss comparing with the true labels or values of the training examples;

3. Use gradient descent to optimize the cost function, and find the parameters in your hypothesis.

4. Use the hypothesis with the found parameters to predict on unseen data.

And we have introduced machine learning library scikit-learn,which has many models already built for you, we can just import linear regression or logistic regression model and fit our training data to learn a model to predict on unseen data. But for deep learning, scikit-learn is not suitable anymore (non GPU optimizations), so we introduced you popular deep learning frameworks Pytorch and TensorFlow.

In this assignment, you will first see how to use scikit-learn to train logistic regression model for assignment 2 data (student admission), and then practice with Pytorch basics and then use Pytorch and TensorFlow to build a neural network model for a house price prediction (regression task) and a neural network model for predicting breast cancer (classification task).

<span style="color:red">To submit</span>: You will need to submit this notebook with proper naming <span style="color:blue">Assignment3_FirstName_LastName.ipynb</span> to blackboard.

<span style="color:red">Important</span>: <span style="color:blue">Remember to restart the kernel everytime you modify your model or training steps</span> Otherwise you may see some strange behavior which may be caused by "model" training being accumulated.

Megan Jen -- March 3, 2022

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

We will again first load the data from assignment 2.

In [2]:
# loading file to array data
data = np.loadtxt('a2data1.txt', delimiter=",")
print(data.shape)
print(data[:5, :])

# get training examples features into X and label to y
X = data[:, :2]
y = data[:, -1]
print(X.shape)
print(y.shape)

(100, 3)
[[34.62365962 78.02469282  0.        ]
 [30.28671077 43.89499752  0.        ]
 [35.84740877 72.90219803  0.        ]
 [60.18259939 86.3085521   1.        ]
 [79.03273605 75.34437644  1.        ]]
(100, 2)
(100,)


## 1. Logistic regression with Scikit-learn
We will first see how to use logistic regression model from scikit-learn library.

In [3]:
from sklearn.linear_model import LogisticRegression

# create model and fit in the data
model = LogisticRegression(max_iter=1000)
model.fit(X, y)

# calcute the training accuracy, 
# you should see 0.89 which is same as your model in assignment 2
train_accuracy = model.score(X, y)
print("Train accuracy is: {}".format(train_accuracy))

Train accuracy is: 0.89


## 2. Three-layer neural network model with Pytorch

Now we will create a three-layer (two hidden layers) neural network model with this dataset again, and compare the training accuracy with Logistic regression model. Before we begin, let's practice with basics of Pytorch: torch.tensor, torch. autograd, torch.nn.Module. The official documentation is <a href="https://pytorch.org/tutorials/beginner/basics/intro.html">here</a>.

In [4]:
# import torch first and print its version
import torch
print("torch version:", torch.__version__) 

# add a random seed so that everytime you run the model it will give similar results
torch.manual_seed(10)

torch version: 1.10.2


### 2.1 Pytorch Tensor
We have discussed that pytorch tensor is just like numpy array but can run on GPUs. So many operations of tensors are similar to numpy arrays, and we can create tensors from list, numpy arrays and convert tensors to numpy arrays.

#### 2.1.1 Initialize a Tensor
Now let's see ways to initialize a Tensor.

##### 2.1.1.1 Directly from data

In [5]:
# 1. Tensors can be created directly from data. 
# The data type is automatically inferred.

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


##### 2.1.1.2 From Numpy arrays

In [6]:
# 2. Tensors can be created from NumPy arrays.
np_array = np.array([[1, 2],[3, 4]])
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
# tensor to numpy
x_array = x_np.numpy()
print(x_array)

[[1 2]
 [3 4]]


##### 2.1.1.3 From another tensor

In [8]:
# 3. From another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# overrides the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4581, 0.4829],
        [0.3125, 0.6150]]) 



#### 2.1.2 Operations on Tensors 

Tensor operations are very similiar to numpy arrays. There built-in functions for tensor multiplication, element-wise mulitplication and so on. You can move a tensor across devices using .to():


In [9]:
# We move our tensor to the GPU if available
t = torch.randn(2)

device = "cuda" if torch.cuda.is_available() else "cpu"
t = t.to(device)

print(" device:\t'{}'".format(t.device))
print(t)

 device:	'cpu'
tensor([-0.3023, -1.2277])


#### 2.1.2.1 Exercise

And some common operations on tensors: 
<tt><p>
torch.matmul(a, b) # multiples torch tensors a and b

a * b      # element-wise multiplication between two torch tensors

torch.eye(n) # creates an identity torch tensor with shape (n, n)

torch.zeros(n, m) # creates a torch tensor of zeros with shape (n, m)

torch.ones(n, m) # creates a torch tensor of ones with shape (n, m)

torch.rand(n, m) # creates a random torch tensor with shape (n, m)
<p></tt>

Now practice with operations with defining two tensors first.

In [10]:
# create tensor of ones with shape (2, 2), assign to tensor_a
tensor_a = torch.ones(2, 2)
# create tensor_b 
tensor_b = tensor_a * 2
print(tensor_a, tensor_a.shape)
print(tensor_b)


tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
tensor([[2., 2.],
        [2., 2.]])


In [11]:
# Exercise create a random tensor with shape (2, 4)
# START CODE HERE
tensor_c = torch.rand(2, 4)
# END CODE HERE

In [12]:
# Exercise torch.matmul(..) function with tensor_a, and tensor_b
# START CODE HERE
torch.matmul(tensor_a, tensor_b)
# END CODE HERE

tensor([[4., 4.],
        [4., 4.]])

#### 2.1.3 Tensor.autograd

We have given the examples for autograd package in class, the following code part is from the slide:

In [13]:
# manually calculate gradients

N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in, device=device)
y = torch.randn(N, D_out, device=device)
w1 = torch.randn(D_in, H, device=device)
w2 = torch.randn(H, D_out, device=device)

learning_rate = 1e-6
for t in range(500):
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)
    loss = (y_pred - y).pow(2).sum()
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2


In [14]:
# With torch.autograd to automatical gradients

N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    loss = (y_pred - y).pow(2).sum()
    
    loss.backward()
    
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        w1.grad.zero_()
        w2.grad.zero_()

#### 2.1.4 Torch.nn

We also talked about high level wrapper torch.nn.Module, and how to define a customized Module to define your neural network model, and how to use torch.optim package to optimize the model. The following code is from the slides in Lecture 7.


In [15]:

class TwoLayerNet(torch.nn.Module): 
    def __init__(self, D_in, H, D_out): 
        super(TwoLayerNet, self).__init__() 
        self.linearl = torch.nn.Linear(D_in, H) 
        self.linear2 = torch.nn.Linear(H, D_out) 
    
    def forward(self, x): 
        h_relu = self.linearl(x).clamp(min=0) 
        ypred = self.linear2(h_relu) 
        return ypred 

N, D_in, H, D_out = 64, 1000, 100, 10 
x = torch.randn(N, D_in) 
y = torch.randn(N, D_out) 

model = TwoLayerNet(D_in, H, D_out) 

optimizer = torch.optim.SGD(model.parameters(), lr=1e-4) 

for t in range(500): 
    ypred = model(x) 
    loss = torch.nn.functional.mse_loss(ypred, y) 
    loss.backward() 
    optimizer.step() 
    optimizer.zero_grad() 


### 2.2 Three-layer neural network for assignment2 data

Now you can follow the example in the above cell to define a neural network model for assignment 2 data. We can build a three-layer neural network model with 16 hidden units for 1st hidden layer, and  8 hidden units on the 2nd hidden layer, and we want the output layer to have sigmoid() function as activation function. First, you will need to figure what's input dimension is, that is how many features each training example has. Recall that we are given two exam scores of one student, so there two features, you don't need to worry about adding the bias or interception anymore, pytorch will do that for you. 

In [16]:
# loading file to array data
data = np.loadtxt('a2data1.txt', delimiter=",")

# get training examples features into X and label to y
X = data[:, :2]
y = data[:, -1]
print(X.shape)
print(y.shape)

(100, 2)
(100,)


First, we create a torch.nn.Module that define this three-layer neural network. We want this three-layer neural network model to have, 16 hidden units for 1st hidden layer, and 8 hidden units on the 2nd hidden layer, and we want the output layer to have sigmoid() function as activation function. We can use torch.nn.Sigmoid() for this.

You can refer to the two-layer model above to define this class.

In [17]:
class ThreeLayerNet(torch.nn.Module):
    def __init__(self, D_in, H_1, H_2, D_out): 
        super(ThreeLayerNet, self).__init__() 
        self.linear1 = torch.nn.Linear(D_in, H_1) 
        self.linear2 = torch.nn.Linear(H_1, H_2)
        
        # START CODE HERE (2 line)
        self.linear3 = torch.nn.Linear(H_2, D_out) 
        self.sigmoid = torch.nn.Sigmoid()
        # END CODE HERE
    
    def forward(self, x): 
        h1_relu = self.linear1(x).clamp(min=0) 
        h2_relu = self.linear2(h1_relu).clamp(min=0)
        
        # STAET CODE HERE (1 ~ 2 line)
        ypred = self.sigmoid(self.linear3(h2_relu))
        # END CODE HERE
        
        return ypred 

Next, we will define input , 1st hidden, 2nd hidden, output dimensions of the model D_in (should be 2), H_1 (16 hidden units), H_2 (8 hidden_units), D_out (should be 1).

In [18]:
# Define input, 1st hidden, 2nd hidden, output dimensions of the model D_in, H_1, H_2, D_out

# STAET CODE HERE (1 line)
D_in, H_1, H_2, D_out = 2, 16, 8, 1
# END CODE HERE

Next, we will initialize a model from the class ThreeLayerNet with dimensions defined above. 


In [19]:
# create a model from class ThreeLayerNet(..) and name it model_3layer

# START CODE HERE (1 line) 
model_3layer = ThreeLayerNet(D_in, H_1, H_2, D_out)
# END CODE HERE

Next, we can use torch.optim to optimize the model. One thing different from our example above is the loss function. Since we are doing classification, we will use cross-entropy loss, more specifically the binary cross-entropy loss that is torch.nn.BCELoss(),  which is essentially the loss function  we used for logistic regression. For multi-class, you will use torch.nn.CrossEntropyLoss().

In [20]:
# converting input to tensors, and converting to float type because of tensor weights type is float 
tensor_X = torch.from_numpy(X).float()

# reshape true labels in y to be same shape as pytorch model's output
tensor_y = torch.from_numpy(y.reshape(100, 1)).float()
tensor_y.shape

torch.Size([100, 1])

In [21]:
optimizer = torch.optim.Adam(model_3layer.parameters(), lr=1e-2) 

for t in range(200):
    # START CODE HERE (1 lines)
    ypred = model_3layer(tensor_X)
    # END CODE HERE
     
    loss_fn = torch.nn.BCELoss() #loss function
    loss = loss_fn(ypred, tensor_y) #calculating loss
    
    # START CODE HERE (2 lines)
    #back propogation
    loss.backward() #back propogation
    optimizer.step() #how to do back propogation in pytorch. this is updating parameters
    # END CODE HERE
     
    optimizer.zero_grad() 



In [22]:
from sklearn.metrics import accuracy_score

# get predictions of the training examples
# and calculate training accuracy
y_hat = ypred.detach().numpy()
train_pred_labels = y_hat >= 0.5
train_accuracy = accuracy_score(train_pred_labels, y)
print("Training accuracy is: {} %".format(train_accuracy * 100))

Training accuracy is: 92.0 %


|Expected|
|:-|
|Training accuracy is: 91.0 % (or somewhere over 90%)|

## 3. TensorFlow exercise

In this section 3, you will practice with TensorFlow. Taken the slides code as examples, and also refer to the official documentation <a href="https://pytorch.org/tutorials/beginner/basics/intro.html">here</a> to build a same three-layer neural network. Train it with the assignment 2 data again, and see whether you will get the same result as the pytorch one or not. 

In [23]:
import tensorflow as tf
print(tf.__version__)

2.8.0


### 3.1 TensorFlow basics
Below are some of basic operations on tensors in tensorflow.

In [36]:
# Create a constant tensor A
A = tf.constant([[1,2],
                  [3,4]])
# Create a Variable tensor B
B = tf.Variable([[5,6],
                 [7,8]])
print(A)
print(B)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>


In [25]:
# Concatenate Two Tensor along the sencond dimension
C = tf.concat([A,B], axis=1)
C

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

In [26]:
# Concatenate Two Tensor along the first dimension
D = tf.concat([A,B], axis=0)
D

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [27]:
# Creates a tensor with all elements set to zero.
E = tf.zeros(shape=[4,3],dtype=tf.float16)
E

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float16)>

In [28]:
# Creates a tensor with all elements set to one.
F = tf.ones(shape=[4,3],dtype=tf.int32)
F

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [29]:
# Creates a tensor with elements sampled from a uniform distribution.
G = tf.random.uniform(shape=[2,6])
G

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0.09022141, 0.24294996, 0.7336577 , 0.81594574, 0.21499443,
        0.6360214 ],
       [0.2569946 , 0.07807779, 0.8118094 , 0.16622162, 0.89384353,
        0.04577541]], dtype=float32)>

In [30]:
# Typecast a tensor
I = H * 100.0
print(I)
J = tf.cast(I, dtype=tf.int32)
print(J)

10000.0
tf.Tensor(10000, shape=(), dtype=int32)


In [31]:
# Matrix multiply
A = tf.constant([[1,2],
                  [3,4]])
x = tf.constant([[2],
                 [3]])
M = tf.matmul(A, x)
print(M)

tf.Tensor(
[[ 8]
 [18]], shape=(2, 1), dtype=int32)


In [32]:
# Element-wise math operation
B = tf.constant([[-1,-2],
                 [-3,-4]])
N = tf.multiply(A,B)
print(N)

tf.Tensor(
[[ -1  -4]
 [ -9 -16]], shape=(2, 2), dtype=int32)


### 3.2 Load the data again and Build the model

See the slides code and also tutorial here for a text classification <a href="https://www.tensorflow.org/tutorials/keras/text_classification">here</a>.

In [33]:
# loading file to array data
data = np.loadtxt('a2data1.txt', delimiter=",")

# get training examples features into X and label to y
X = data[:, :2]
y = data[:, -1]
print(X.shape)
print(y.shape)

(100, 2)
(100,)


Build the model.

In [35]:
model_tf = tf.keras.Sequential()

model_tf.add(tf.keras.layers.Dense(16, input_shape=(2,), activation="relu"))
model_tf.add(tf.keras.layers.Dense(8, input_shape=(16,), activation="relu"))

# Fill the blank
model_tf.add(tf.keras.layers.Dense(1, input_shape=(8,), activation="sigmoid"))

optimizer = tf.optimizers.Adam(1e-2)

model_tf.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),optimizer=optimizer, metrics=tf.metrics.BinaryAccuracy())

history = model_tf.fit(X, y, epochs=400, batch_size=100)

Epoch 1/400
1/1 [==============================] - 1s 1s/step - loss: 2.5740 - binary_accuracy: 0.6000
Epoch 2/400
1/1 [==============================] - 0s 11ms/step - loss: 1.7594 - binary_accuracy: 0.6000
Epoch 3/400
1/1 [==============================] - 0s 84ms/step - loss: 1.1981 - binary_accuracy: 0.6000
Epoch 4/400
1/1 [==============================] - 0s 16ms/step - loss: 0.8940 - binary_accuracy: 0.6000
Epoch 5/400
1/1 [==============================] - 0s 13ms/step - loss: 0.7450 - binary_accuracy: 0.6000
Epoch 6/400
1/1 [==============================] - 0s 15ms/step - loss: 0.6467 - binary_accuracy: 0.6200
Epoch 7/400
1/1 [==============================] - 0s 22ms/step - loss: 0.6698 - binary_accuracy: 0.5800
Epoch 8/400
1/1 [==============================] - 0s 19ms/step - loss: 0.7386 - binary_accuracy: 0.4600
Epoch 9/400
1/1 [==============================] - 0s 8ms/step - loss: 0.7555 - binary_accuracy: 0.4500
Epoch 10/400
1/1 [==============================] - 0s 9ms

1/1 [==============================] - 0s 14ms/step - loss: 0.5540 - binary_accuracy: 0.6900
Epoch 79/400
1/1 [==============================] - 0s 12ms/step - loss: 0.5517 - binary_accuracy: 0.6900
Epoch 80/400
1/1 [==============================] - 0s 5ms/step - loss: 0.5510 - binary_accuracy: 0.6800
Epoch 81/400
1/1 [==============================] - 0s 7ms/step - loss: 0.5453 - binary_accuracy: 0.6900
Epoch 82/400
1/1 [==============================] - 0s 12ms/step - loss: 0.5489 - binary_accuracy: 0.6700
Epoch 83/400
1/1 [==============================] - 0s 11ms/step - loss: 0.5422 - binary_accuracy: 0.6800
Epoch 84/400
1/1 [==============================] - 0s 15ms/step - loss: 0.5445 - binary_accuracy: 0.6900
Epoch 85/400
1/1 [==============================] - 0s 11ms/step - loss: 0.5432 - binary_accuracy: 0.6900
Epoch 86/400
1/1 [==============================] - 0s 14ms/step - loss: 0.5388 - binary_accuracy: 0.6700
Epoch 87/400
1/1 [==============================] - 0s 16ms/s

Epoch 155/400
1/1 [==============================] - 0s 9ms/step - loss: 0.3274 - binary_accuracy: 0.8900
Epoch 156/400
1/1 [==============================] - 0s 15ms/step - loss: 0.3277 - binary_accuracy: 0.9000
Epoch 157/400
1/1 [==============================] - 0s 11ms/step - loss: 0.3296 - binary_accuracy: 0.8600
Epoch 158/400
1/1 [==============================] - 0s 8ms/step - loss: 0.3239 - binary_accuracy: 0.8900
Epoch 159/400
1/1 [==============================] - 0s 11ms/step - loss: 0.3170 - binary_accuracy: 0.8800
Epoch 160/400
1/1 [==============================] - 0s 19ms/step - loss: 0.3143 - binary_accuracy: 0.8900
Epoch 161/400
1/1 [==============================] - 0s 25ms/step - loss: 0.3144 - binary_accuracy: 0.9100
Epoch 162/400
1/1 [==============================] - 0s 11ms/step - loss: 0.3132 - binary_accuracy: 0.8900
Epoch 163/400
1/1 [==============================] - 0s 13ms/step - loss: 0.3075 - binary_accuracy: 0.9300
Epoch 164/400
1/1 [====================

1/1 [==============================] - 0s 26ms/step - loss: 0.2859 - binary_accuracy: 0.8400
Epoch 232/400
1/1 [==============================] - 0s 15ms/step - loss: 0.2181 - binary_accuracy: 0.9200
Epoch 233/400
1/1 [==============================] - 0s 17ms/step - loss: 0.2250 - binary_accuracy: 0.9000
Epoch 234/400
1/1 [==============================] - 0s 26ms/step - loss: 0.2598 - binary_accuracy: 0.8600
Epoch 235/400
1/1 [==============================] - 0s 24ms/step - loss: 0.1977 - binary_accuracy: 0.9500
Epoch 236/400
1/1 [==============================] - 0s 14ms/step - loss: 0.2384 - binary_accuracy: 0.9000
Epoch 237/400
1/1 [==============================] - 0s 21ms/step - loss: 0.2121 - binary_accuracy: 0.9300
Epoch 238/400
1/1 [==============================] - 0s 25ms/step - loss: 0.2026 - binary_accuracy: 0.9200
Epoch 239/400
1/1 [==============================] - 0s 42ms/step - loss: 0.2280 - binary_accuracy: 0.9000
Epoch 240/400
1/1 [==============================] 

1/1 [==============================] - 0s 11ms/step - loss: 0.1485 - binary_accuracy: 0.9700
Epoch 308/400
1/1 [==============================] - 0s 12ms/step - loss: 0.1481 - binary_accuracy: 0.9700
Epoch 309/400
1/1 [==============================] - 0s 53ms/step - loss: 0.1475 - binary_accuracy: 0.9700
Epoch 310/400
1/1 [==============================] - 0s 14ms/step - loss: 0.1471 - binary_accuracy: 0.9700
Epoch 311/400
1/1 [==============================] - 0s 8ms/step - loss: 0.1466 - binary_accuracy: 0.9700
Epoch 312/400
1/1 [==============================] - 0s 13ms/step - loss: 0.1465 - binary_accuracy: 0.9700
Epoch 313/400
1/1 [==============================] - 0s 15ms/step - loss: 0.1457 - binary_accuracy: 0.9700
Epoch 314/400
1/1 [==============================] - 0s 10ms/step - loss: 0.1453 - binary_accuracy: 0.9700
Epoch 315/400
1/1 [==============================] - 0s 27ms/step - loss: 0.1449 - binary_accuracy: 0.9700
Epoch 316/400
1/1 [==============================] -

1/1 [==============================] - 0s 17ms/step - loss: 0.1201 - binary_accuracy: 0.9900
Epoch 384/400
1/1 [==============================] - 0s 13ms/step - loss: 0.1199 - binary_accuracy: 0.9900
Epoch 385/400
1/1 [==============================] - 0s 23ms/step - loss: 0.1196 - binary_accuracy: 0.9900
Epoch 386/400
1/1 [==============================] - 0s 16ms/step - loss: 0.1193 - binary_accuracy: 0.9900
Epoch 387/400
1/1 [==============================] - 0s 13ms/step - loss: 0.1191 - binary_accuracy: 0.9900
Epoch 388/400
1/1 [==============================] - 0s 12ms/step - loss: 0.1189 - binary_accuracy: 0.9900
Epoch 389/400
1/1 [==============================] - 0s 19ms/step - loss: 0.1186 - binary_accuracy: 0.9900
Epoch 390/400
1/1 [==============================] - 0s 17ms/step - loss: 0.1182 - binary_accuracy: 0.9900
Epoch 391/400
1/1 [==============================] - 0s 13ms/step - loss: 0.1180 - binary_accuracy: 0.9900
Epoch 392/400
1/1 [==============================] 

model.fit() returns a History object that contains a dictionary with everything that happened during training. We can use this values to plot the loss and training accuracy with respect iterations.

In [ ]:
history_dict = history.history
history_dict.keys()

In [ ]:
acc = history_dict['binary_accuracy']
loss = history_dict['loss']

epochs = range(1, len(acc) + 1)

# "bo" is for "blue dot"
plt.plot(epochs, loss, 'b', label='Training loss')
plt.title('Training loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.show()

In [ ]:
plt.plot(epochs, acc, 'r', label='Training acc')

plt.title('Training accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(loc='lower right')

plt.show()